name: Atualizar README com dados privados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # roda a cada 12 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Atualizar README com dados privados
        uses: anuraghazra/github-readme-stats@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
