name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:     # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: "header, repositories, languages, activity"
          plugin_languages: yes
          plugin_languages_count_private: yes
          plugin_activity: yes
          plugin_activity_limit: 30
          plugin_activity_days: 365
          plugin_activity_visibility: all
          config_display: grid
          config_theme: radical
          output: metrics.svg
