name: GitHub Metrics
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 5      # Mostra apenas top 5 linguagens
          plugin_activity: yes
          plugin_activity_limit: 5       # Mostra apenas 5 atividades recentes
          plugin_repositories: yes
          plugin_repositories_limit: 7   # Limita aos seus 7 repositórios
          config_display: grid
          
      - name: Move file to root
        run: |
          mv metrics_renders/github-metrics.svg .
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add github-metrics.svg
          git commit -m "Update metrics" || echo "Sem alterações"
          git push
